import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';
import { getApiUrl } from '@/lib/utils';
import { toast } from 'sonner';

type Language = 'en' | 'cs';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
  tPlan: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// --- Translation Dictionary ---
const translations: Record<Language, Record<string, Record<string, string>>> = {
  en: {
    common: {
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      logout: "Logout",
      loading: "Loading...",
      backToDashboard: "Back to Dashboard",
      profile: "Profile",
      logout: "Logout",
      clientDetails: "Client Details",
      clientDetailsDesc: "Personalized fitness data and program",
      profileInfo: "Profile Information",
      none: "None"
    },
    sidebar: {
      training: "Training",
      nutrition: "Nutrition",
      lifestyle: "Lifestyle",
      progress: "Progress",
      sessions: "Sessions",
      support: "Coach Support",
      myProfile: "My Profile",
      signOut: "Sign Out"
    },
    dashboard: {
      title: "Dashboard",
      noPlan: "No Plan Generated",
      noPlanDesc: "You haven't completed your onboarding profile yet. Generate your plan now or wait for your trainer to set it up for you.",
      startOnboarding: "Start Onboarding"
    },
    tabs: {
      trainingPlan: "Training Plan",
      personalizedProgram: "Your personalized program",
      calories: "Calories",
      protein: "Protein",
      trainingDays: "Training Days",
      habits: "Habits",
      perWeek: "/week",
      daily: "daily",
      weeklySplit: "Weekly Training Split",
      exercises: "exercises",
      rest: "Rest",
      nutritionPlan: "Nutrition Plan",
      dailyTargets: "Daily targets and macronutrient breakdown",
      meals: "Meals",
      hydration: "Hydration",
      carbs: "Carbs",
      fat: "Fat",
      lifestyleHabits: "Lifestyle & Habits",
      sleepAndStress: "Sleep, stress and daily routines",
      progressTracking: "Progress Tracking",
      logWorkoutData: "Log your workout and nutrition data to see your progress.",
      logWorkout: "Log Workout",
      workoutHistory: "Workout History",
      trainingSessions: "Training Sessions",
      bookSession: "Book and manage your 1-on-1 sessions",
      coachSupport: "Coach Support",
      sendMessage: "Send Message",
      typeMessage: "Type your message...",
      dailyCalorieTarget: "Daily Calorie Target",
      macroBreakdown: "Macro Breakdown",
      macroDistribution: "Macro Distribution",
      suggestedMeals: "Suggested Meals",
      personalizedTips: "Personalized Tips",
      sleepOptimization: "Sleep Optimization",
      motivationStrategy: "Motivation Strategy",
      stressManagement: "Stress Management",
      dailyHabits: "Daily Habits",
      disciplineTips: "Discipline Tips",
      recoveryProtocol: "Recovery Protocol",
      weeklyCheckpoints: "Weekly Checkpoints",
      mindsetShift: "Mindset Shift",
      
      // Tracking
      logDate: "Log Date",
      totalLogsToday: "Total Logs Today",
      logExercise: "Log Exercise",
      exerciseName: "Exercise Name",
      sets: "Sets",
      reps: "Reps",
      weight: "Weight",
      addSet: "Add Set",
      todaysLog: "Today's Log",
      dailyCalories: "Daily Calories",
      totalCaloriesConsumed: "Total Calories Consumed",
      saveNutrition: "Save Nutrition",
      recordedFor: "Recorded for",

      // Support
      coachSupportTitle: "Coach Support",
      coachSupportDesc: "Have a question about your plan, diet, or training progress? Ask our coaching team directly.",
      sendAMessage: "Send a Message",
      weReplyWithin24h: "We typically reply within 24 hours.",
      supportMessageLabel: "Support Message",
      supportMessageDesc: "Your message will be delivered to your assigned coach or the central admin support.",
      typeMessageAdmin: "Message support...",
      typeMessageCoach: "Message coach...",
      sending: "Sending...",
      send: "Send",
      yourMessages: "Your Messages",
      noMessagesYet: "You haven't sent any messages yet.",
      you: "You",
      adminReply: "Admin Reply",
      coachReply: "Coach Reply",
      awaitingReply: "Awaiting reply...",
      msgSentAdmin: "Message sent to admin!",
      msgSentCoach: "Message sent to coach!",
      sendError: "Error sending: ",

      // Booking Calendar
      availableSlots: "Available Slots",
      selectClient: "Select Client",
      chooseClient: "Choose a client...",
      busy: "Busy",
      selectClientFirst: "Please select a client first",
      sessionBooked: "Session booked successfully!",
      failedToBook: "Failed to book session"
    },
    plan: {
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snacks: "Snacks",
      preWorkout: "Pre-Workout",
      postWorkout: "Post-Workout"
    },
    profile: {
      myProfile: "My Profile",
      accountSecurity: "Account Security",
      changePassword: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm New Password",
      notCompleted: "You haven't completed your profile yet.",
      clientNotCompleted: "Client hasn't completed onboarding yet.",
      backToDashboard: "Back to Dashboard",
      logout: "Logout",
      avatar: "Avatar",
      goToAdmin: "Go to Admin Panel",
      managedByTrainer: "This data is managed by your trainer or admin.",
      actionRequired: "Action Required: App Update",
      retakeQuestionnaire: "Retake Full Questionnaire",
      goalsAndExperience: "Goals & Experience",
      nutritionInfo: "Nutrition Info",
      favorites: "Favorites",
      dislikes: "Dislikes"
    },
    trainer: {
      myClients: "My Clients",
      schedule: "Schedule",
      messages: "Messages",
      trainerDashboard: "Trainer Dashboard",
      activeClient: "Active Client",
      messageClient: "Message Client",
      noClientsAssigned: "No clients assigned to you yet.",
      confirmedSessions: "Confirmed Sessions",
      noUpcomingSessions: "No upcoming sessions.",
      yourResponse: "Your response",
      typeYourReply: "Type your reply...",
      sendReply: "Send Reply",
      reply: "Reply",
      editClientPlan: "Edit Client Plan",
      createClientPlan: "Create Client Plan",
      replySent: "Reply sent successfully",
      msgSentAdmin: "Message sent to Admin!",
      msgSentCoach: "Message sent to Coach!",
      errorSendingReply: "Failed to send reply",
      sendMessageDesc: "Send a direct message to your client."
    },
    admin: {
      manageClients: "Manage Clients",
      manageTrainers: "Manage Trainers",
      messaging: "Messaging",
      commHub: "Communication Hub",
      commHubDesc: "Select a conversation from the sidebar to view thread history and respond to inquiries.",
      supportChannel: "Support Channel",
      systemResponse: "System Response",
      msgSentSuccess: "Reply sent successfully",
      msgSentError: "Failed to send reply",
      onboardNewTrainer: "Onboard New Trainer",
      onboardTrainerDesc: "Grant professional access to a new team member",
      trainerUsername: "Trainer Username",
      trainerPassword: "Trainer Password",
      onboardButton: "Onboard Trainer",
      clientHeader: "Client",
      trainerAssignmentHeader: "Trainer Assignment",
      actionsHeader: "Actions",
      unassigned: "Unassigned",
      assignTrainer: "Assign Trainer",
      changeTrainer: "Change Trainer",
      noMessagesYet: "No messages in this hub yet.",
      selectChat: "Select a chat to start messaging",
      typeMessage: "Type your message..."
    },
    landing: {
      tags: "Free · Science-Based · Sustainable",
      title1: "Your body deserves ",
      title2: "a real plan.",
      subtitle: "No gimmicks. No overpriced subscriptions. Just honest, personalized training, nutrition, and lifestyle plans built on real experience.",
      goToDashboard: "Go to Dashboard",
      login: "Login",
      logout: "Logout",
      getStarted: "Get Started",
      startPlan: "Start Your Plan",
      learnMore: "Learn More",
      featTitle1: "Everything you need. ",
      featTitle2: "Nothing you don't.",
      featSubtitle: "A complete system that covers training, nutrition, and the mindset shifts that actually make lasting change.",
      f1Title: "Personalized Plans",
      f1Desc: "Training programs tailored to your goals, experience, and lifestyle.",
      f2Title: "Nutrition Guidance",
      f2Desc: "Calorie targets, macro breakdowns, and sustainable meal structures.",
      f3Title: "Lifestyle Coaching",
      f3Desc: "Discipline, motivation, sleep, and habit-building strategies.",
      f4Title: "Progress Tracking",
      f4Desc: "Log workouts, track calories, and visualize your transformation.",
      ctaTitle: "Ready to build a better version of yourself?",
      ctaDesc: "Complete a detailed onboarding and get your personalized plan in minutes. No credit card. No catches.",
      getFreePlan: "Get Your Free Plan",
      footerDesc: "Built on real experience. No gimmicks, no shortcuts."
    },
    onboarding: {
      personalData: "Personal Data",
      tellUsAbout: "Tell us about yourself",
      age: "Age",
      gender: "Gender",
      male: "Male",
      female: "Female",
      other: "Other",
      height: "Height (cm)",
      weight: "Weight (kg)",
      bodyType: "What is your body type?",
      skinny: "Very Skinny",
      skinnyDesc: "Low muscle and fat mass",
      lean: "Lean",
      leanDesc: "Thin build with low muscle",
      normal: "Normal",
      normalDesc: "Average physique",
      athletic: "Athletic",
      athleticDesc: "Visible muscle, low fat",
      shredded: "Shredded",
      shreddedDesc: "Extremely low fat, high muscle",
      mildOverweight: "Overweight",
      mildOverweightDesc: "Carry extra weight around midsection",
      obese: "Obese",
      obeseDesc: "Significantly overweight",
      extremelyObese: "Very Obese",
      extremelyObeseDesc: "High health risk profile",
      fitnessGoals: "Fitness Goals",
      whatAchieve: "What do you want to achieve?",
      buildMuscle: "Build Muscle",
      loseFat: "Lose Fat",
      getStronger: "Get Stronger",
      improveEndurance: "Improve Endurance",
      stayHealthy: "Stay Healthy",
      fitnessLevel: "Fitness Level",
      howExperienced: "How experienced are you?",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Expert",
      dietaryPref: "Dietary Preferences",
      dietaryPreference: "Dietary Preference",
      anyDiet: "Any specific diet?",
      none: "None",
      vegetarian: "Vegetarian",
      vegan: "Vegan",
      pescatarian: "Pescatarian",
      keto: "Keto",
      paleo: "Paleo",
      omnivore: "Omnivore",
      allergiesIntolerances: "Allergies / Intolerances",
      lactose: "Lactose",
      gluten: "Gluten",
      nuts: "Nuts",
      soy: "Soy",
      seafood: "Seafood",
      allergies: "Allergies / Dislikes",
      whatToAvoid: "What should we avoid?",
      healthLimitations: "Health Limitations",
      injuries: "Any injuries or conditions?",
      lowerBackPain: "Lower Back Pain",
      kneeIssues: "Knee Issues",
      missingKnee: "Missing Knee",
      shoulderIssues: "Shoulder Issues",
      limitedMobility: "Limited Mobility",
      neckPain: "Neck Pain",
      wristIssues: "Wrist Issues",
      elbowIssues: "Elbow Issues",
      hipIssues: "Hip Issues",
      asthma: "Asthma",
      obstaclesTitle: "Barriers & Strengths",
      obstaclesSubtitle: "Understand what helps and hinders you",
      obstaclesFace: "Which obstacles do you face?",
      lackOfTime: "Lack of Time",
      lowMotivation: "Low Motivation",
      highStress: "High Stress",
      inconsistentRoutine: "Inconsistent Routine",
      poorDiet: "Poor Diet Habits",
      otherLimitations: "Other Physical Limits",
      advantagesHave: "Which advantages do you have?",
      gymAccess: "Gym Access",
      homeEquipment: "Home Equipment",
      timeFlexibility: "Time Flexibility",
      prevExperience: "Previous Experience",
      lifestyleTitle: "Lifestyle & Routine",
      lifestyleSubtitle: "Optimizing your daily habits",
      trainingFrequency: "Training Frequency",
      freq12: "1-2 days / week",
      freq34: "3-4 days / week",
      freq56: "5-6 days / week",
      preferredDuration: "Preferred Workout Duration",
      under30: "Under 30 min",
      "30-45": "30-45 min",
      "45-60": "45-60 min",
      over60: "Over 60 min",
      disciplineLevel: "Discipline Level",
      motivationLevel: "Motivation Level",
      sleepQuality: "Sleep Quality",
      poor: "Poor",
      average: "Average",
      good: "Good",
      activityLevel: "Activity Level",
      sedentary: "Sedentary",
      lightActive: "Lightly Active",
      modActive: "Moderately Active",
      veryActive: "Very Active",
      stressLevel: "Stress Level",
      low: "Low",
      moderate: "Moderate",
      high: "High",
      proactivityLevel: "Proactivity",
      selfDevelopment: "Self-Development",
      perfectionismLevel: "Perfectionism",
      nutritionTitle: "Nutrition Strategy",
      nutritionSubtitle: "Fueling your transformation",
      budgetLimitations: "Budget Limitations",
      tightBudget: "Tight / Budget-Friendly",
      eatingHabits: "Current Eating Habits",
      structuredHabit: "Structured",
      intuitiveHabit: "Intuitive",
      socialHabit: "Social Eater",
      emotionalHabit: "Emotional Eater",
      mealFrequency: "Preferred Meal Frequency",
      "2meals": "2 large meals",
      "3meals": "3 regular meals",
      "4meals": "3 meals + 1 snack",
      "5plusMeals": "5+ small meals",
      calorieAwarenessLabel: "Calorie Awareness",
      basic: "Basic",
      experienced: "Experienced",
      favoriteFoods: "Favorite Foods",
      favoriteFoodsPlaceholder: "Steak, Pasta, Fruit...",
      dislikedFoods: "Disliked Foods",
      dislikedFoodsPlaceholder: "Broccoli, Liver...",
      planPreference: "Plan Preference",
      planStyleSubtitle: "How do you want your program?",
      planStructure: "Plan Structure",
      simplePlan: "Simple & Effective",
      simplePlanDesc: "Focus on main movements, minimal complexity",
      structuredStrict: "Structured & Strict",
      structuredStrictDesc: "Detailed sets, reps, and precise timing",
      flexibleApproach: "Flexible & Balanced",
      flexibleApproachDesc: "Adaptable recommendations for busy people",
      selectAllApply: "Select all that apply",
      generatingTitle: "Building Your Plan...",
      generatingDesc: "Analyzing your data and creating a personalized program.",
      complete: "Complete Profile",
      back: "Back",
      home: "Home",
      continue: "Continue",
      generatePlan: "Generate My Plan",
      step: "Step",
      of: "of",
      none: "None",
      errAgeMin: "Age must be at least 10",
      errAgeMax: "Age must be less than 120",
      errHeightMin: "Height must be realistic (min 80cm)",
      errHeightMax: "Height must be realistic (max 250cm)",
      errWeightMin: "Weight must be realistic (min 30kg)",
      errWeightMax: "Weight must be realistic (max 300kg)",
      errSelectGender: "Please select a gender",
      errSelectFitnessLevel: "Please select a fitness level",
      errLongDescription: "Description is too long",
      errSelectGoal: "Please select at least one goal",
      errSelectSleepQuality: "Please select sleep quality",
      errSelectActivityLevel: "Please select activity level",
      errSelectStressLevel: "Please select stress level",
      errSelectProactivity: "Please select proactivity level",
      errInputTooLong: "Input is too long (max 150 chars)",
      errSelectDietaryPref: "Please select dietary preference",
      errSelectBudget: "Please select budget limitation",
      errSelectEatingHabits: "Please select eating habits",
      errSelectMealFreq: "Please select meal frequency",
      errSelectCalorieAwareness: "Please select calorie awareness",
      errSelectPlanStyle: "Please select a plan style"
    }
  },
  cs: {
    common: {
      save: "Uložit",
      cancel: "Zrušit",
      edit: "Upravit",
      logout: "Odhlásit",
      loading: "Načítání...",
      backToDashboard: "Zpět na přehled",
      profile: "Profil",
      logout: "Odhlásit se",
      clientDetails: "Detaily Klienta",
      clientDetailsDesc: "Personalizovaná fitness data a program",
      profileInfo: "Informace o Profilu",
      none: "Žádná"
    },
    sidebar: {
      training: "Trénink",
      nutrition: "Strava",
      lifestyle: "Životní styl",
      progress: "Progres",
      sessions: "Lekce",
      support: "Podpora trenéra",
      myProfile: "Můj Profil",
      signOut: "Odhlásit se"
    },
    dashboard: {
      title: "Přehled",
      noPlan: "Žádný plán",
      noPlanDesc: "Ještě jste nevyplnili svůj profil. Vytvořte si plán hned teď nebo počkejte, až vám ho nasadí trenér.",
      startOnboarding: "Vyplnit profil"
    },
    tabs: {
      trainingPlan: "Tréninkový plán",
      personalizedProgram: "Váš program na míru",
      calories: "Kalorie",
      protein: "Bílkoviny",
      trainingDays: "Tréninkové dny",
      habits: "Návyky",
      perWeek: "/týdně",
      daily: "denně",
      weeklySplit: "Týdenní rozpis",
      exercises: "cviků",
      rest: "Pauza",
      nutritionPlan: "Stravovací plán",
      dailyTargets: "Denní cíle a rozložení makroživin",
      meals: "Jídla",
      hydration: "Hydratace",
      carbs: "Sacharidy",
      fat: "Tuky",
      lifestyleHabits: "Životní styl & Návyky",
      sleepAndStress: "Spánek, stres a denní rutina",
      progressTracking: "Sledování pokroku",
      logWorkoutData: "Zaznamenávejte své tréninky a stravu pro přehled o pokroku.",
      logWorkout: "Zapsat trénink",
      workoutHistory: "Historie tréninků",
      trainingSessions: "Osobní lekce",
      bookSession: "Rezervujte a spravujte své 1-on-1 lekce",
      coachSupport: "Podpora trenéra",
      sendMessage: "Odeslat zprávu",
      typeMessage: "Napište zprávu...",
      dailyCalorieTarget: "Denní limit kalorií",
      macroBreakdown: "Zastoupení makroživin",
      macroDistribution: "Rozložení makroživin",
      suggestedMeals: "Doporučený jídelníček",
      personalizedTips: "Osobní doporučení",
      sleepOptimization: "Optimalizace spánku",
      motivationStrategy: "Strategie motivace",
      stressManagement: "Zvládání stresu",
      dailyHabits: "Každodenní návyky",
      disciplineTips: "Tipy k disciplíně",
      recoveryProtocol: "Regenerační protokol",
      weeklyCheckpoints: "Týdenní checkpointy",
      mindsetShift: "Změna myšlení",

      // Tracking
      logDate: "Datum záznamu",
      totalLogsToday: "Celkem záznamů dnes",
      logExercise: "Zapsat trénink",
      exerciseName: "Název cviku",
      sets: "Série",
      reps: "Opakování",
      weight: "Váha",
      addSet: "Přidat sérii",
      todaysLog: "Dnešní záznam",
      dailyCalories: "Denní kalorie",
      totalCaloriesConsumed: "Zkonzumované kalorie celkem",
      saveNutrition: "Uložit stravu",
      recordedFor: "Záznam pro",

      // Support
      coachSupportTitle: "Podpora Trenéra",
      coachSupportDesc: "Máte otázku k plánu, stravě nebo pokroku? Zeptejte se přímo trenéra klientské podpory.",
      sendAMessage: "Odeslat zprávu",
      weReplyWithin24h: "Obvykle odpovídáme do 24 hodin.",
      supportMessageLabel: "Zpráva pro podporu",
      supportMessageDesc: "Vaše zpráva bude doručena trenérovi, nebo na centrální podporu administrátorů.",
      typeMessageAdmin: "Napište zprávu podpoře...",
      typeMessageCoach: "Napište zprávu trenérovi...",
      sending: "Odesílám...",
      send: "Odeslat",
      yourMessages: "Vaše zprávy",
      noMessagesYet: "Zatím jste neodeslali žádné zprávy.",
      you: "Vy",
      adminReply: "Odpověď Admina",
      coachReply: "Odpověď Trenéra",
      awaitingReply: "Čeká se na odpověď...",
      msgSentAdmin: "Zpráva odeslána administrátorovi!",
      msgSentCoach: "Zpráva odeslána trenérovi!",
      sendError: "Chyba při odesílání: ",

      // Booking Calendar
      availableSlots: "Dostupné termíny",
      selectClient: "Vyberte klienta",
      chooseClient: "Zvolte klienta...",
      busy: "Obsazeno",
      selectClientFirst: "Prosím, zejdříve vyberte klienta.",
      sessionBooked: "Lekce úspěšně zarezervována!",
      failedToBook: "Chyba při rezervaci lekce"
    },
    plan: {
      monday: "Pondělí",
      tuesday: "Úterý",
      wednesday: "Středa",
      thursday: "Čtvrtek",
      friday: "Pátek",
      saturday: "Sobota",
      sunday: "Neděle",
      breakfast: "Snídaně",
      lunch: "Oběd",
      dinner: "Večeře",
      snacks: "Svačiny",
      preWorkout: "Před tréninkem",
      postWorkout: "Po tréninku"
    },
    profile: {
      myProfile: "Můj Profil",
      accountSecurity: "Zabezpečení účtu",
      changePassword: "Změnit heslo",
      currentPassword: "Současné heslo",
      newPassword: "Nové heslo",
      confirmPassword: "Potvrdit heslo",
      notCompleted: "Zatím jste si nevyplnili profil.",
      clientNotCompleted: "Klient zatím nedokončil svůj profil.",
      backToDashboard: "Zpět na Přehled",
      logout: "Odhlásit",
      avatar: "Avatar",
      goToAdmin: "Přejít do Admin Panelu",
      managedByTrainer: "Tyto údaje spravuje Váš trenér nebo administrátor.",
      actionRequired: "Vyžadována akce: Aktualizace aplikace",
      retakeQuestionnaire: "Znovu vyplnit dotazník",
      goalsAndExperience: "Cíle a zkušenosti",
      nutritionInfo: "Informace ke stravě",
      favorites: "Oblíbené",
      dislikes: "Neoblíbené"
    },
    trainer: {
      myClients: "Moji Klienti",
      schedule: "Rozvrh",
      messages: "Zprávy",
      trainerDashboard: "Trenérský Přehled",
      activeClient: "Aktivní Klient",
      messageClient: "Poslat Zprávu",
      noClientsAssigned: "Zatím nemáte přiřazené žádné klienty.",
      confirmedSessions: "Potvrzené Lekce",
      noUpcomingSessions: "Žádné nadcházející lekce.",
      yourResponse: "Vaše odpověď",
      typeYourReply: "Napište svou odpověď...",
      sendReply: "Odeslat Odpověď",
      reply: "Odpovědět",
      editClientPlan: "Upravit Plán Klienta",
      createClientPlan: "Vytvořit Plán pro Klienta",
      replySent: "Odpověď úspěšně odeslána",
      msgSentAdmin: "Zpráva odeslána administrátorovi!",
      msgSentCoach: "Zpráva odeslána trenérovi!",
      errorSendingReply: "Chyba při odesílání odpovědi",
      sendMessageDesc: "Pošlete napřímo zprávu tomuto klientovi."
    },
    admin: {
      manageClients: "Správa Klientů",
      manageTrainers: "Správa Trenérů",
      messaging: "Messaging",
      commHub: "Komunikační Centrum",
      commHubDesc: "Vyberte konverzaci z bočního panelu pro zobrazení historie a odpověď.",
      supportChannel: "Support Kanál",
      systemResponse: "Systémová Odpověď",
      msgSentSuccess: "Odpověď úspěšně odeslána",
      msgSentError: "Chyba při odesílání odpovědi",
      onboardNewTrainer: "Registrovat Nového Trenéra",
      onboardTrainerDesc: "Udělit profesionální přístup novému členovi týmu",
      trainerUsername: "Uživatelské jméno trenéra",
      trainerPassword: "Heslo trenéra",
      onboardButton: "Registrovat Trenéra",
      clientHeader: "Klient",
      trainerAssignmentHeader: "Přiřazený Trenér",
      actionsHeader: "Akce",
      unassigned: "Nepřiřazeno",
      assignTrainer: "Přiřadit Trenéra",
      changeTrainer: "Změnit Trenéra",
      noMessagesYet: "V tomto centru zatím nejsou žádné zprávy.",
      selectChat: "Vyberte chat pro zahájení komunikace",
      typeMessage: "Napište zprávu..."
    },
    landing: {
      tags: "Zdarma · Vědecky podloženo · Udržitelně",
      title1: "Tvé tělo si zaslouží ",
      title2: "skutečný plán.",
      subtitle: "Žádné nesmysly. Žádné předražené plány. Pouze upřímný, osobní trénink, strava a životní styl postavený na reálných datech.",
      goToDashboard: "Přejít na Přehled",
      login: "Přihlášení",
      logout: "Odhlásit",
      getStarted: "Začít",
      startPlan: "Spustit Váš Plán",
      learnMore: "Zjistit Více",
      featTitle1: "Vše co potřebujete. ",
      featTitle2: "Nic víc.",
      featSubtitle: "Kompletní systém, který pokrývá trénink, stravu a změnu myšlení potřebnou k dosažení cílů.",
      f1Title: "Plány na míru",
      f1Desc: "Tréninkové programy na míru vašim cílům, zkušenostem a životnímu stylu.",
      f2Title: "Vedení ve stravování",
      f2Desc: "Cílové kalorie, rozložení makroživin a udržitelná struktura jídel.",
      f3Title: "Životní styl",
      f3Desc: "Disciplína, motivace, spánek a budování zdravých návyků.",
      f4Title: "Sledování pokroku",
      f4Desc: "Zápisy tréninků, kalorií a vizualizace vaší proměny.",
      ctaTitle: "Jste připraveni začít?",
      ctaDesc: "Vyplňte detailní dotazník a získejte osobní plán během chvilky. Žádné skryté poplatky.",
      getFreePlan: "Získejte plán zdarma",
      footerDesc: "Postaveno na reálných zkušenostech. Žádné zkratky."
    },
    onboarding: {
      personalData: "Osobní údaje",
      tellUsAbout: "Řekněte nám něco o sobě",
      age: "Věk",
      gender: "Pohlaví",
      male: "Muž",
      female: "Žena",
      other: "Jiné",
      height: "Výška (cm)",
      weight: "Váha (kg)",
      bodyType: "Jakou máte postavu?",
      skinny: "Velmi hubená",
      skinnyDesc: "Velmi nízké množství svalů i tuku",
      lean: "Hubená",
      leanDesc: "Štíhlá postava, málo svalů",
      normal: "Normální",
      normalDesc: "Průměrná postava",
      athletic: "Atletická",
      athleticDesc: "Viditelné svaly, nízký tuk",
      shredded: "Vysekaná",
      shreddedDesc: "Extrémně nízký tuk, hodně svalů",
      mildOverweight: "Nadváha",
      mildOverweightDesc: "Více tuku v oblasti břicha/boků",
      obese: "Obézní",
      obeseDesc: "Výrazná nadváha",
      extremelyObese: "Extrémně obézní",
      extremelyObeseDesc: "Vysoké riziko zdravotních potíží",
      fitnessGoals: "Fitness cíle",
      whatAchieve: "Čeho chcete dosáhnout?",
      buildMuscle: "Nabrání svalů",
      loseFat: "Redukce tuku",
      getStronger: "Zesílení",
      improveEndurance: "Zlepšení kondice",
      stayHealthy: "Zdraví",
      fitnessLevel: "Úroveň",
      howExperienced: "Jaké máte zkušenosti?",
      beginner: "Začátečník",
      intermediate: "Pokročilý",
      advanced: "Expert",
      dietaryPref: "Stravovací preference",
      dietaryPreference: "Preference stravy",
      anyDiet: "Dodržujete speciální dietu?",
      none: "Žádná",
      vegetarian: "Vegetarián",
      vegan: "Vegan",
      pescatarian: "Pescatarian",
      keto: "Keto",
      paleo: "Paleo",
      omnivore: "Všežravec",
      allergiesIntolerances: "Alergie / Intolerance",
      lactose: "Laktóza",
      gluten: "Lepek",
      nuts: "Ořechy",
      soy: "Sója",
      seafood: "Mořské plody",
      allergies: "Alergie / Nechutná",
      whatToAvoid: "Čemu se vyhnout?",
      healthLimitations: "Zdravotní omezení",
      injuries: "Zranění nebo nemoci?",
      lowerBackPain: "Bolest beder",
      kneeIssues: "Problémy s koleny",
      missingKnee: "Chybějící koleno",
      shoulderIssues: "Problémy s rameny",
      limitedMobility: "Omezená mobilita",
      neckPain: "Bolest za krkem",
      wristIssues: "Problémy s zápěstím",
      elbowIssues: "Problémy s lokty",
      hipIssues: "Problémy s kyčlemi",
      asthma: "Astma",
      obstaclesTitle: "Bariéry a silné stránky",
      obstaclesSubtitle: "Pochopte, co vám pomáhá a co vás brzdí",
      obstaclesFace: "Jakým překážkám čelíte?",
      lackOfTime: "Nedostatek času",
      lowMotivation: "Nízká motivace",
      highStress: "Vysoký stres",
      inconsistentRoutine: "Nekonzistentní rutina",
      poorDiet: "Špatné stravovací návyky",
      otherLimitations: "Jiná fyzická omezení",
      advantagesHave: "Jaké máte výhody?",
      gymAccess: "Přístup do fitka",
      homeEquipment: "Domácí vybavení",
      timeFlexibility: "Časová flexibilita",
      prevExperience: "Předchozí zkušenosti",
      lifestyleTitle: "Životní styl a rutina",
      lifestyleSubtitle: "Optimalizace vašich denních návyků",
      trainingFrequency: "Frekvence tréninku",
      freq12: "1-2 dny v týdnu",
      freq34: "3-4 dny v týdnu",
      freq56: "5-6 dní v týdnu",
      preferredDuration: "Preferovaná délka tréninku",
      under30: "Pod 30 min",
      "30-45": "30-45 min",
      "45-60": "45-60 min",
      over60: "Nad 60 min",
      disciplineLevel: "Úroveň disciplíny",
      motivationLevel: "Úroveň motivace",
      sleepQuality: "Kvalita spánku",
      poor: "Špatná",
      average: "Průměrná",
      good: "Dobrá",
      activityLevel: "Úroveň aktivity",
      sedentary: "Sedavý",
      lightActive: "Mírně aktivní",
      modActive: "Středně aktivní",
      veryActive: "Velmi aktivní",
      stressLevel: "Úroveň stresu",
      low: "Nízká",
      moderate: "Střední",
      high: "Vysoká",
      proactivityLevel: "Proaktivita",
      selfDevelopment: "Seberozvoj",
      perfectionismLevel: "Perfekcionismus",
      nutritionTitle: "Strategie stravování",
      nutritionSubtitle: "Palivo pro vaši proměnu",
      budgetLimitations: "Omezení rozpočtu",
      tightBudget: "Nízký rozpočet",
      eatingHabits: "Současné stravovací návyky",
      structuredHabit: "Strukturované",
      intuitiveHabit: "Intuitivní",
      socialHabit: "Společenský jedlík",
      emotionalHabit: "Emoční jedlík",
      mealFrequency: "Preferovaná frekvence jídel",
      "2meals": "2 velká jídla",
      "3meals": "3 běžná jídla",
      "4meals": "3 jídla + 1 svačina",
      "5plusMeals": "5+ malých jídel",
      calorieAwarenessLabel: "Znalost kalorií",
      basic: "Základní",
      experienced: "Pokročilá",
      favoriteFoods: "Oblíbená jídla",
      favoriteFoodsPlaceholder: "Steak, Těstoviny, Ovoce...",
      dislikedFoods: "Neoblíbená jídla",
      dislikedFoodsPlaceholder: "Brokolice, Játra...",
      planPreference: "Preference plánu",
      planStyleSubtitle: "Jak chcete mít program?",
      planStructure: "Struktura plánu",
      simplePlan: "Jednoduchý a efektivní",
      simplePlanDesc: "Zaměření na hlavní cviky, minimální složitost",
      structuredStrict: "Strukturovaný a striktní",
      structuredStrictDesc: "Detailní série, opakování a přesné načasování",
      flexibleApproach: "Flexibilní a vyvážený",
      flexibleApproachDesc: "Přizpůsobitelná doporučení pro zaneprázdněné lidi",
      selectAllApply: "Vyberte vše, co platí",
      generatingTitle: "Tvorba plánu...",
      generatingDesc: "Analyzujeme vaše data a sestavujeme personalizovaný program.",
      complete: "Dokončit Profil",
      back: "Zpět",
      home: "Domů",
      continue: "Pokračovat",
      generatePlan: "Vygenerovat můj plán",
      step: "Krok",
      of: "z",
      none: "Žádná",
      errAgeMin: "Věk musí být alespoň 10 let",
      errAgeMax: "Věk musí být méně než 120 let",
      errHeightMin: "Výška musí být realistická (min 80cm)",
      errHeightMax: "Výška musí být realistická (max 250cm)",
      errWeightMin: "Váha musí být realistická (min 30kg)",
      errWeightMax: "Váha musí být realistická (max 300kg)",
      errSelectGender: "Prosím vyberte pohlaví",
      errSelectFitnessLevel: "Prosím vyberte úroveň kondice",
      errLongDescription: "Popis je příliš dlouhý",
      errSelectGoal: "Prosím vyberte alespoň jeden cíl",
      errSelectSleepQuality: "Prosím vyberte kvalitu spánku",
      errSelectActivityLevel: "Prosím vyberte úroveň aktivity",
      errSelectStressLevel: "Prosím vyberte úroveň stresu",
      errSelectProactivity: "Prosím vyberte úroveň proaktivity",
      errInputTooLong: "Text je příliš dlouhý (max 150 znaků)",
      errSelectDietaryPref: "Prosím vyberte stravovací preference",
      errSelectBudget: "Prosím vyberte rozpočtové omezení",
      errSelectEatingHabits: "Prosím vyberte stravovací návyky",
      errSelectMealFreq: "Prosím vyberte frekvenci jídel",
      errSelectCalorieAwareness: "Prosím vyberte znalost kalorií",
      errSelectPlanStyle: "Prosím vyberte styl plánu"
    }
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user, token } = useAuth();
  
  const [language, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('fitforge-lang');
    return (saved === 'cs' || saved === 'en') ? saved : 'en';
  });

  // Sync with user preference from DB upon login
  useEffect(() => {
    if (user && (user as any).language) {
      if ((user as any).language === 'cs' || (user as any).language === 'en') {
        setLangState((user as any).language);
        localStorage.setItem('fitforge-lang', (user as any).language);
      }
    }
  }, [user]);

  const setLanguage = async (lang: Language) => {
    setLangState(lang);
    localStorage.setItem('fitforge-lang', lang);

    // Sync to remote profile if logged in
    if (token) {
        try {
            await fetch(getApiUrl("/api/user/settings"), {
                method: "PUT",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${token}`
                },
                body: JSON.stringify({ language: lang })
            });
        } catch (e) {
            console.error("Failed to sync language preference remotely");
        }
    }
  };

  const t = (key: string, section: string = 'common') => {
    return translations[language]?.[section]?.[key] || key;
  };

  const tPlan = (key: string) => {
    // Used specifically to cleanly translate capitalized database strings like days/meals
    const lowerKey = key.toLowerCase().replace(/[^a-z0-9]/g, '');
    const mapMatch = Object.keys(translations.en.plan).find(k => k.toLowerCase() === lowerKey);
    return mapMatch ? (translations[language]?.plan?.[mapMatch] || key) : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tPlan }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
